[package]
name = "nightbug"
description = "A Lisp-like language"
version = "0.1.0"
authors = ["Ruby Lazuli <nipkraps@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
annotate-snippets = { version = "0.9.0", features = ["color"] }
thiserror = "1.0.20"

[profile.release]
lto = true
