unstable_features = true
brace_style = "PreferSameLine"
format_macro_matchers = true
format_macro_bodies = true
match_block_trailing_comma = true
newline_style = "Unix"
overflow_delimited_expr = true
trailing_comma = "Never"
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true
