unstable_features = true
format_macro_matchers = true
format_macro_bodies = true
match_block_trailing_comma = true
newline_style = "Unix"
trailing_comma = "Never"
use_field_init_shorthand = true
wrap_comments = true
